# This file was generated by GoReleaser. DO NOT EDIT.
cask "arielsurco-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "63b1b6fe007e818551e188bef062eec23cf2abee246c2e50d98d7723e82f3573"
    end
    on_arm do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "937e873492f4a0ce14b36ad5570bc15a83ae70868cb8aebbe77554231bd0845b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "5ec7d78f5d96bcbbbd6beee8367e68e2818743fee1cb5cf3d96d6deb2aacae94"
    end
    on_arm do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "f34df5d32c12f3125755ee3949e49d18a4c01475af7e5f7b83f360f803ecb56d"
    end
  end

  name "arielsurco-cli"
  desc "Personal developer CLI with project navigation and TUI"
  homepage "https://github.com/ArielSurco/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arielsurco-cli"

  # No zap stanza required

end
