# This file was generated by GoReleaser. DO NOT EDIT.
cask "arielsurco-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "8e101d757a25d56d124a278af6138f9d8bb148372a645eade742c562f249ea8f"
    end
    on_arm do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "5e7d8652dc7af1ef46e00fe4333e17ab249ba9bf26142772a6ac1b44ca0ea3c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "92ccee8b9e6c1fa171b2b25bc1054ce0447d723ce03a9194e34621b824aac3b4"
    end
    on_arm do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "be54d945830d011f305087b53ce9cbdf0c9643b4f071f2654f3acf722ce8d683"
    end
  end

  name "arielsurco-cli"
  desc "Personal developer CLI with project navigation and TUI"
  homepage "https://github.com/ArielSurco/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arielsurco-cli"

  # No zap stanza required

end
