# This file was generated by GoReleaser. DO NOT EDIT.
cask "arielsurco-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "b2a773d13ab547c94c12f2e946c32e4ea38f9c350b9ab9b94faadf19bfb5e498"
    end
    on_arm do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "f7c374354a1c0a6f11f686a510575f68bca123480ce4ff9a84abe9b59552e2af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "0e6919183b2ec94dd3b5bf2b70da5370e22ec3e4287e75061be2addabdef0843"
    end
    on_arm do
      url "https://github.com/ArielSurco/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "d10b044190bb9c05c8c74828a97868869ab422eb57a5793e7ecdb811827d1afb"
    end
  end

  name "arielsurco-cli"
  desc "Personal developer CLI with project navigation and TUI"
  homepage "https://github.com/ArielSurco/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arielsurco-cli"

  # No zap stanza required

end
