# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArielsurcoCli < Formula
  desc "Personal developer CLI with project navigation and TUI"
  homepage "https://github.com/ArielSurco/cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ArielSurco/cli/releases/download/v0.1.0/cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "4bdfb02714bb358ad5c03e266c406d40e6ec18f27e42db104e915b78cfe08318"

      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ArielSurco/cli/releases/download/v0.1.0/cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "1687da46221505b58652a45477bb1f1ff2a3de325a9eb1e285e5cde0b3a51dee"

      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArielSurco/cli/releases/download/v0.1.0/cli_0.1.0_linux_amd64.tar.gz"
      sha256 "5c4b057d267b753f3e46d8400bc0228c886396f13c2130c3e7f1a5b215daead0"
      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArielSurco/cli/releases/download/v0.1.0/cli_0.1.0_linux_arm64.tar.gz"
      sha256 "62badf29efb8062dd63a704be7d7202592eb1af75506702e67a5bd81497c5c56"
      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
  end

  test do
    system "#{bin}/arielsurco-cli", "--version"
  end
end
