# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArielsurcoCli < Formula
  desc "Personal developer CLI with project navigation and TUI"
  homepage "https://github.com/ArielSurco/homebrew-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ArielSurco/homebrew-cli/releases/download/v0.2.0/homebrew-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "75b1b1b64d537268d1c5786fe1f22947e1608a55c1cf1b8fb36457827aa70af0"

      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ArielSurco/homebrew-cli/releases/download/v0.2.0/homebrew-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "78481aadb8337a48a272e6d5204897a3c24466da6240ecea174a355d5a205593"

      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArielSurco/homebrew-cli/releases/download/v0.2.0/homebrew-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "bd8a85954c0f8efe3b9fc633403dd412ff961e2c70b532bdbbf963368cd3852d"
      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArielSurco/homebrew-cli/releases/download/v0.2.0/homebrew-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "6511eed5c769871017ccdc9d724e5d47d6b391e30e5646ccb2ed17d709e2d027"
      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
  end

  test do
    system "#{bin}/arielsurco-cli", "--version"
  end
end
