# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ArielsurcoCli < Formula
  desc "Personal developer CLI with project navigation and TUI"
  homepage "https://github.com/ArielSurco/cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ArielSurco/cli/releases/download/v0.2.0/cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "aff1083e479818675940610ff85295e6e1d284c4eaf23b5ba0de2355e1d5e5cc"

      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ArielSurco/cli/releases/download/v0.2.0/cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "946b3963395d89db6d9932d351c7ed2127f797019c6e2ca78b95e0f2741f7421"

      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArielSurco/cli/releases/download/v0.2.0/cli_0.2.0_linux_amd64.tar.gz"
      sha256 "08ddc6e4eae39f1a37675a102d1cf699df1a4f7080dd9af27a3aac5ce316c39a"
      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ArielSurco/cli/releases/download/v0.2.0/cli_0.2.0_linux_arm64.tar.gz"
      sha256 "07f9eca1c26f4ea6531c7b259af9bfef6d2ce45b16b898681396ca2af21727ae"
      define_method(:install) do
        bin.install "arielsurco-cli"
      end
    end
  end

  test do
    system "#{bin}/arielsurco-cli", "--version"
  end
end
